services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    networks:
      - carbon-calculator

networks:
  carbon-calculator:
    driver: bridge
